version: "3.9"

services:
  pipeline:
    build: .
    environment:
      - url=file_server:3000/yellow_tripdata_2021-01.csv
      - user=root
      - password=root
      - host=db
      - port=5432
      - db=ny_taxi
      - table=taxi
    depends_on:
      - file_server
      - db
    networks:
      - pipeline-network

  file_server:
    image: "python:3.8-slim-buster"
    command: ['python', '-m', 'http.server', '3000']
    working_dir: "/files"
    volumes:
      - "./data:/files"
    networks:
      - pipeline-network

  db:
    image: "postgres:15"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    networks:
      - pipeline-network

  pgAdmin:
    image: "dpage/pgadmin4"
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - pipeline-network
    depends_on:
      - db
  

networks:
  pipeline-network: